services:
  postgres:
    image: postgres:17
    container_name: uae_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_uae_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: alexflames77/uae_etl:latest
    container_name: uae_api
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "${API_PORT}:8010"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_uae_data:
